### PR TITLE
Module 3 Group Project Space Travel Hub

### PR DESCRIPTION
**Pull request by the-catalystmc**
In this project we:
- Created React App.
- Installed React Redux, Redux Logger and React Router.
- Downloaded the free image for the app logo.
- Created routes and view components (Rockets, Missions, My Profile. Use <NavLink /> for the page navigation links and style active class to indicate which section/page user is currently on (underline active navigation link).
- Created directories for all Redux state slice files (rockets, missions).
- Fetched data and update Redux store
- Used useSelector() Redux Hook to select the state slices and render lists of rockets and missions in corresponding routes
- Wrote actions and reducers for booking rockets and joining missions
- Wrote actions and reducers for canceling rockets and leaving missions
- Rendered UI: conditional components rendering
- Rendered UI: My Profile section
- Wrote Unit tests

## Initial Video Link https://youtu.be/H9IJYPeTtNw

### CODE REVIEW

**Comment by Davidosky007** [comment]
## Hi @the-catalystmc @sevinchek 👋, 

Good job so far! 💪 
* Great job implementing the optional requirements 👏 
* The repo looks professional.✔️
* Git/GitHub flow best practices have been followed✔️
* There are no linter errors✔️
## There are some issues that you still need to work on to go to the next project but you are almost there!

There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
* I suggest you share the highlighted code piece you found interesting while working on this project ( for example like you mentioned in the video how you were proud of working on the conditional rendering of rockets) you can show that piece code 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by the-catalystmc** [comment]
@Davidosky007 Thank you for your great review.
You should also highlight some interesting piece of code **_or something you built that you are very proud of_**.
If the above requirement is what you are mentioning, we did highlight what we built that we were proud of in the video. It does not have to be code.

**Review by vichuge — APPROVED** [review]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

InbornCandidHornet-size_restricted

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Temmarie** [comment]
Hello 👋,

This is an additional review as a result of the second opinion request.

Looks like the issue was resolved here, so I have nothing else to say other than best of luck with the rest of your projects!

Keep rocking 🚀!

**Pull request merged**
